### ISSUE TITLE
Refresh issue in codesandbox

### ISSUE THREAD

**Issue by calpeyser** [jtessler/studio-multiplayer-game#25]
We found errors while editing a GameComponent subclass in codesandbox.  The error would occur seemingly at random, and would be temporarily fixed by reloading the home page and creating a new game instance.

I don't remember the precise error message, but it had to do with the superclass constructor.  I believe the line 

creator: props.location.state.creator || "",

failed,  because either probs.location or props.location.state were undefined.

**Comment by jtessler** [comment]
Haven't run into any crashes while testing these commits in codesandbox.io. Marking as fixed.
